services:
  tprep-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - prometheus
      - grafana
    networks:
      - my_network

  mongo:
    image: mongo:8.0.3
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${MONGO_DIR}:/data/db
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  my_network: