services:
  tprep-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    networks:
      - my_network

  mongo:
    image: mongo:8.0.3
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${MONGO_DIR}:/data/db
    networks:
      - my_network

networks:
  my_network: