global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'tprep-server'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['tprep-server:3000']

  - job_name: minio-job
    bearer_token_file: /etc/prometheus/prometheus_bearer
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']