global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'tprep-server'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['tprep-server:3000']

  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoidEtVSFNQTXFsSGZJeVhlTmpzaVEiLCJleHAiOjQ4OTgwMjkzMjh9.DalQ7pMi4Fs4Qej7wxcG4_CkY1u0OY_R1IOwP-iF7meSHcn1WQ0Flz89UBp0D-ESYXZcuRUKfQXQyMv9j_2HuA
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: [ 'minio:9000' ]